version: 1.2
workflows:
   - subclass: wdl
     primaryDescriptorPath: /helloworld.wdl
     testParameterFiles:
         - /helloworld.wdl.json
   - name: secondwdl
     subclass: wdl
     primaryDescriptorPath: /helloworld2.wdl
     testParameterFiles:
         - /helloworld.wdl.json
